### ISSUE TITLE
Position and Intensity

### ISSUE THREAD

**Issue by bchen34** [timmassingham/CifTools#3]
Is there a way to get the position (x,y) and intensity data from the .cif files using CifTools?

**Comment by timmassingham** [comment]
I'm afraid the cluster positions aren't stored in the CIF files, I believe they are / were in a suplementary text file in the sequencing directory.  There may have been an update to the file format since the software was written; `ciftools` is a decade old and I am prevented from working on projects related to Illumina's technology due to my employment at one of their rivals.
